version: "3"

services:
  app:
    container_name: rickandmortyapi_backend
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/rickandmortyapi
      - app-gems:/app-gems
    # env_file:
    #   - ".env"

volumes:
  app-gems:
